spring.application.name=api-usuarios
# conexão com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/api_usuarios
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# driver
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.hibernate.ddl-auto=update

# mostrar SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true